//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by C:\Project\night\appleinpc\aipc.rc
//
#define IDC_DEFAULT                     3
#define IDD_ABOUTBOX                    100
#define IDR_APPLE2                      104
#define ID_INDICATOR_CLOCK_SPEED        106
#define ID_INDICATOR_FRAME_SPEED        107
#define ID_INDICATOR_DISK               108
#define IDR_MAINFRAME                   128
#define IDR_APPLE2TYPE                  129
#define IDD_DEBUG                       130
#define IDD_CONFIGURE_SLOT              131
#define IDD_CONFIGURE_DISK              132
#define IDR_CONFIG_SLOT                 133
#define IDD_CONFIGURE_MONITOR           135
#define IDD_CONFIGURE_COLOR             135
#define IDR_TOOLBAR                     138
#define IDB_DISK                        140
#define IDB_DISK_OFF                    146
#define IDB_DISK_READ                   147
#define IDB_DISK_WRITE                  148
#define IDC_CURSOR1                     149
#define IDB_DISK_OFF_F                  149
#define IDC_CURSOR2                     150
#define IDB_DISK_READ_F                 150
#define IDD_CONFIGURE_SOUND             151
#define IDB_DISK_WRITE_F                151
#define IDD_CONFIGURE_MOCKINGBOARD      152
#define IDR_ACCELERATOR                 154
#define IDD_CONFIGURE                   157
#define IDD_CONFIGURE_SD_DISK           158
#define IDI_ICON1                       162
#define IDI_ICON2                       163
#define IDC_LIST_PROCESS                1000
#define IDC_EDIT_FILENAME2              1001
#define IDC_BTN_SLOT1                   1002
#define IDC_EIDT_DATA                   1003
#define IDC_STATIC2                     1004
#define IDC_LIST_REGISTERS              1005
#define IDC_STATIC3                     1006
#define IDC_BTN_INSERTSLOT1             1007
#define IDC_CHK_DISK1                   1008
#define IDC_FLAGBOX                     1009
#define IDC_EDIT_FILENAME1              1010
#define IDC_SLIDER_HUE                  1011
#define IDC_FLAG_N                      1012
#define IDC_BTN_BROWSE1                 1013
#define IDC_SLIDER_BRIGHTNESS           1014
#define IDC_FLAG_V                      1015
#define IDC_BTN_BROWSE2                 1016
#define IDC_SLIDER_SATURATION           1017
#define IDC_FLAG_EXTEND                 1018
#define IDC_CHK_DISK2                   1019
#define IDC_EDIT_HUE                    1020
#define IDC_FLAG_B                      1021
#define IDC_EDIT_SATURATION             1022
#define IDC_MASTER_VOLUME               1023
#define IDC_FLAG_D                      1024
#define IDC_EDIT_BRIGHTNESS             1025
#define IDC_MASTER_VOLUME2              1026
#define IDC_RIGHT_VOLUME                1026
#define IDC_FLAG_I                      1027
#define IDC_MASTER_MUTE                 1028
#define IDC_SPEAKER_MUTE                1029
#define IDC_ENHANCED_DISK1              1029
#define IDC_SAMPLE_RATE                 1030
#define IDC_ENHANCED_DISK2              1030
#define IDC_LEFT_MUTE                   1030
#define IDC_STATIC_PROCESS              1031
#define IDC_RIGHT_MUTE                  1031
#define IDC_SPEAKER_VOLUME              1032
#define IDC_LEFT_VOLUME                 1032
#define IDC_BTN_SLOT2                   1033
#define IDC_STATIC_DATA                 1034
#define IDC_BTN_SLOT3                   1035
#define IDC_STATIC_SLOT                 1035
#define IDC_BUTTON_TRACE                1036
#define IDC_BTN_SLOT4                   1037
#define IDC_FLAG_Z                      1038
#define IDC_BTN_SLOT5                   1039
#define IDC_FLAG_C                      1040
#define IDC_BTN_SLOT6                   1041
#define IDC_BTN_SLOT7                   1042
#define IDC_BTN_INSERTSLOT2             1043
#define IDC_BTN_INSERTSLOT3             1044
#define IDC_BTN_INSERTSLOT4             1045
#define IDC_BTN_INSERTSLOT5             1046
#define IDC_BTN_INSERTSLOT6             1047
#define IDC_BTN_INSERTSLOT7             1048
#define IDC_BTN_SLOT8                   1049
#define IDC_BTN_INSERTSLOT8             1050
#define IDC_JOYSTICK                    1051
#define IDC_MONITOR_TYPE                1052
#define IDC_SCAN_FREQ                   1053
#define IDC_BTN_COLOR                   1054
#define IDC_BTN_MONITOR                 1055
#define IDC_BTN_SOUND                   1056
#define IDC_MASTER_BALANCE              1059
#define IDC_SPEAKER_BALANCE             1063
#define IDC_KEYBOARD_REPEAT             1067
#define IDC_KEYBOARD_DELAY              1068
#define IDC_JOYSTICK_NONE               1070
#define IDC_JOYSTICK_NUMPAD             1071
#define IDC_JOYSTICK_PCJOY              1072
#define IDC_JOYSTICK_PCJOYSTICK         1072
#define IDC_VIDEO_COLOR                 1073
#define IDC_VIDEO_FREQ                  1074
#define IDC_VIDEO_PREVIEW               1078
#define IDC_MACHINE                     1080
#define IDC_MACHINE_2PLUS               1081
#define IDC_MACHINE_2E                  1082
#define IDC_PHASOR_MOCKING              1082
#define IDC_MACHINE_2C                  1083
#define IDC_PHASOR_NATIVE               1083
#define IDC_PHASOR_BALANCE              1084
#define IDC_PHASOR_VOLUME               1085
#define IDC_PHASOR_MUTE                 1086
#define IDC_COLOR0                      1090
#define IDC_COLOR1                      1091
#define IDC_COLOR2                      1092
#define IDC_COLOR3                      1093
#define IDC_COLOR4                      1094
#define IDC_COLOR5                      1095
#define IDC_COLOR6                      1096
#define IDC_COLOR7                      1097
#define IDC_COLOR8                      1098
#define IDC_COLOR9                      1099
#define IDC_COLOR10                     1100
#define IDC_COLOR11                     1101
#define IDC_COLOR12                     1102
#define IDC_COLOR13                     1103
#define IDC_COLOR14                     1104
#define IDC_COLOR15                     1105
#define IDC_COLOR_SETTING               1109
#define IDC_COLOR_MODE0                 1110
#define IDC_COLOR_MODE1                 1111
#define IDC_COLOR_MODE2                 1112
#define IDC_COLOR_MODE3                 1113
#define IDC_PREVIEW                     1114
#define IDC_COLOR_NAME0                 1115
#define IDC_COLOR_NAME3                 1116
#define IDC_COLOR_NAME6                 1117
#define IDC_COLOR_NAME9                 1118
#define IDC_COLOR_NAME12                1119
#define IDC_COLOR_NAME15                1120
#define IDC_VIDEO_H                     1121
#define IDC_JOYDEAD                     1121
#define IDC_VIDEO_S                     1122
#define IDC_JOYSAT                      1122
#define IDC_VIDEO_B                     1123
#define IDC_SCANLINE                    1124
#define ID_DEBUG                        32771
#define ID_CONFIGURE_SLOTS              32772
#define ID_REBOOT                       32773
#define ID_MONITOR                      32774
#define ID_POWER                        32775
#define ID_POWERON                      32776
#define ID_BUTTON32779                  32777
#define ID_POWEROFF                     32778
#define ID_BUTTON32781                  32779
#define ID_RESET                        32780
#define ID_FULL_SCREEN                  32787
#define ID_2XSCREEN                     32788
#define ID_DISKETTE                     32789
#define ID_BUTTON32792                  32792
#define ID_HARDDISK                     32793
#define ID_SCANLINE                     32794
#define ID_SLOT_NONE                    33000
#define ID_SLOT_DISK                    33001
#define ID_SLOT_MOCKINGBOARD            33002
#define ID_SLOT_PHASOR                  33003
#define ID_SLOT_MOUSE                   33004
#define IDC_SLOT1                       33010
#define IDC_SLOT2                       33011
#define IDC_SLOT3                       33012
#define IDC_SLOT4                       33013
#define IDC_SLOT5                       33014
#define IDC_SLOT6                       33015
#define IDC_SLOT7                       33016
#define IDC_SLOT1_SETUP                 33020
#define IDC_SLOT2_SETUP                 33021
#define IDC_SLOT3_SETUP                 33022
#define IDC_SLOT4_SETUP                 33023
#define IDC_SLOT5_SETUP                 33024
#define IDC_SLOT6_SETUP                 33025
#define IDC_SLOT7_SETUP                 33026
#define IDS_NO_ROMFILE                  57638
#define IDS_INVALID_ROMFILE_LENGTH      57639
#define IDS_ROMFILE_READ_ERROR          57645
#define IDC_STATIC1                     65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
